name: webview_in_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/www/index.html
    - assets/www/styles/style.css