name: spotmusic
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-22.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  fpdart: ^2.0.0-dev.3
  shared_preferences: ^2.2.3
  dotted_border: ^2.1.0
  flex_color_picker: ^3.5.0
  file_picker: ^8.0.3
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.38
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  just_audio_background: ^0.0.1-beta.12
  flutter_bloc: ^8.1.1
  pocketbase: ^0.18.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
